### ISSUE TITLE
build resources doesn't expand groups

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#121]
```
topology:
  grp1:
    edel:
      control: 1 
  grp[2-6]:
    edel:
      compute: 10
```

is loaded as 

```
resources:
  edel:
    control: 1
    compute: 10
```

instead of 
```
resources:
  edel:
    control: 1
    compute: 50
```
