### ISSUE TITLE
Make the registry configuration homogeneous

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#142]
We got now several methods for deploying the registry. These are not homogeneous in the way we express them in the configuration.
I propose to have something like : 

```
registry:
  type: internal | external | ceph | None
  options
```
options will differ from one method to another : 

### internal 

```
registry:
  type: internal
  # no options as a first guess
```

Note that port=4000 is hard-coded (collision with keystone when running on the controller).  We could maybe expose it here.

### external

```
registry:
  type: external
  address: 
  port: 
```

### ceph

```
registry:
  type: ceph
  ceph_keyring: 
  ceph_id: 
  ceph_rbd: 
  ceph_mon_host: 
```

## None

No registry, use the public one for all docker instances.

validation of this part may occur in the framework side and if not present a default value maybe enforced in `enos/enos.py`
