### ISSUE TITLE
nest resource description in the provider definition

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#167]
Example : 

```
provider:
  type: vagrant
  box: debian/contrib-jessie64
  resources:
    extra-large:
      control: 1
    medium:
      network: 1
    tiny:
      compute: 1
```
