### ISSUE TITLE
reservation.yaml.sample isn't sync with master

### ISSUE THREAD

**Issue by msimonin** [BeyondTheClouds/enos#187]
This should be : 
```
# Repository
kolla_repo: "https://git.openstack.org/openstack/kolla-ansible"
kolla_ref: "master"

# Vars : globals.yml
kolla:
  kolla_base_distro: centos
  kolla_install_type: source
  docker_namespace: beyondtheclouds
  openstack_release: latest
  enable_heat: no
```
