### ISSUE TITLE
[Rally] Creating a new VM try to use public instead of private network

### ISSUE THREAD

**Issue by rcherrueau** [BeyondTheClouds/enos#215]
When executing rally `NovaServers.boot_and_list_server`, the booted VM tries to use public instead of private network. See `neutron-server.log` on network node:
```
ERROR neutron.plugins.ml2.managers [req-fb01a6a3-efe8-438a-a47f-2069e62c27a6 8edba6e3eefb47c483aa331cde3dcb15 9c43891eae9941b7aa58390d7400b54a - default default] Failed to *bind port* 760a99ba-b3fe-4875-b28f-6270ea3d73a5 on host econome-9-kavlan-4.nantes.grid5000.fr for vnic_type normal using segments [{'network_id': 'be5d9299-dd47-43f7-9819-99e0c99de0a3', 'segmentation_id': None, 'physical_network': u'physnet1', 'id': 'fdbb9dc5-cab2-4f43-bb78-5484b149c9d0', 'network_type': u'flat'}]
```

Network ID `be5d9299-dd47-43f7-9819-99e0c99de0a3` refers to public network. 

### Step to reproduce
```
enos deploy # on a node with one nic
enos bench
```

You can also directly call the rally scenario from docker
```
docker run -v /root/rally_home:/home/rally/data xrally/xrally-openstack:latest task start /home/rally/data/nova-boot-list-cc.yml --task-args-file /home/rally/data/rally-args.json --deployment discovery
```

**Comment by rcherrueau** [comment]
This may be relative to the `nics` arguments in the nova python sdk when you create a server.
https://docs.openstack.org/python-novaclient/latest/reference/api/novaclient.v2.servers.html#novaclient.v2.servers.ServerManager.create

I don't know what the rally client tries to do with that `nics`: 
https://github.com/openstack/rally/blob/565947d453d93756ffd9c011d5ba93cdd6488754/rally/plugins/openstack/scenarios/nova/utils.py#L72-L78

**Comment by rcherrueau** [comment]
The private net seems unseen by nova in the rally context.

With `nics: [{net-id: <private-net>}]`, rally scenario says the network doesn't exist. With `nics: [{net-id: <public-net>}]`, rally scenario tries to start a vm and fails as expected.

**Comment by rcherrueau** [comment]
Setting the private net to a shared one fixes the issue (ie, `openstack network set --share private`). But the `nics: [{net-id: <private-net>}]` is still needed. Whereas, I got the following error:
```
Conflict: Multiple possible networks found, use a Network ID to be more specific.
```

Adding `auto_assign_nic: true` instande of `nics: ...` doesn't help.

**Comment by rcherrueau** [comment]
Should try by explicitly specifying to create the network:

```yaml
  NovaServers.boot_and_list_server:
  - ...
  user:
   ...
   network:
      start_cidr: "10.2.0.0/24"
      networks_per_tenant: 2
```


See, https://github.com/openstack/rally/blob/2102b6eeea1d5cab89a1aba75b43f050e9ba421d/samples/tasks/scenarios/nova/boot-and-delete.yaml#L37-L39https://github.com/openstack/rally/blob/2102b6eeea1d5cab89a1aba75b43f050e9ba421d/samples/tasks/scenarios/nova/boot-and-delete.yaml#L37-L39

**Comment by rcherrueau** [comment]
It works with the combination of `auto_assign_nic: true` and the creation of the network.
```yaml
NovaServers.boot_and_list_server:
-
      args:
        ...
        detailed: true
        auto_assign_nic: true
      ...
    context:
      network:
        start_cidr: "10.2.0.0/24"
        networks_per_tenant: 1
```
