### ISSUE TITLE
Docker registry configuration is ignored by Kolla

### ISSUE THREAD

**Issue by jonglezb** [BeyondTheClouds/enos#345]
The [docker registry configuration](https://beyondtheclouds.github.io/enos/customization/index.html#docker-registry-mirror-configuration) in `reservation.yaml` is no longer taken into account by Kolla.

For instance, with the following configuration in Grid'5000, the docker cache is never actually used:
```
registry:
  ip: docker-cache.grid5000.fr
  port: 80
  type: external
```

From https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=13121#c2 this is what happens:

```
TASK [baremetal : Merge custom docker config] **********************************
ok: [grisou-25-kavlan-7.nancy.grid5000.fr]
ok: [grisou-24-kavlan-7.nancy.grid5000.fr]
ok: [grisou-20-kavlan-7.nancy.grid5000.fr]

TASK [baremetal : Write docker config] *****************************************
--- before: /etc/docker/daemon.json
+++ after: /home/ajenkins/.ansible/tmp/ansible-local-8216xd3w41m0/tmptugzcdoc
@@ -1,5 +1,6 @@
 {
-  "debug": true,
-  "registry-mirrors": ["[http://docker-cache.lille.grid5000.fr:80](http://docker-cache.lille.grid5000.fr/)"],
-  "insecure-registries": ["[http://docker-cache.lille.grid5000.fr:80](http://docker-cache.lille.grid5000.fr/)"]
+    "log-opts": {
+        "max-file": "5",
+        "max-size": "50m"
+    }
 }
\ No newline at end of file
```

It's caused by this change in Kolla : https://opendev.org/openstack/kolla-ansible/commit/a5808ad8ba8e0c9cd02d5f4ec3e1f073c332a7d3

**Comment by jonglezb** [comment]
In the Grid'5000 bug report above, @msimonin suggested the following workaround, which works:

```
kolla:
  docker_custom_config:
    registry-mirrors:
      - "http://docker-cache.grid5000.fr"
    insecure-registries:
      - "http://docker-cache.grid5000.fr"
```

Either we need to document this workaround, or fix the bug and make sure that Kolla takes our configuration into account.
